package com.app.citysparsh.model;

public enum OfficerDepartment {
    ROADS_AND_TRANSPORTATION,
    ELECTRICAL_SERVICES,
    WATER_SUPPLY_AND_DRAINAGE,
    SANITATION_AND_WASTE_MANAGEMENT,
    PARKS_AND_HORTICULTURE,
    BUILDINGS_AND_MAINTENANCE,
    GENERAL
}
